# FROM rocm/pytorch:rocm7.2_ubuntu22.04_py3.10_pytorch_release_2.7.1
FROM docker.io/rocm/pytorch:rocm7.1_ubuntu22.04_py3.11_pytorch_release_2.9.1

WORKDIR /workspace/GPT-SoVITS/
#SHELL ["/bin/bash", "-c"]
USER root

RUN apt-get update \
    && apt-get install --no-install-recommends -y \
    build-essential \
    cmake \
    unzip \
    ffmpeg \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY --chown=root:root Docker /workspace/GPT-SoVITS/Docker

RUN mv /workspace/GPT-SoVITS/Docker/Fortinet_CA_SSL.crt /usr/local/share/ca-certificates \
    && ls -la /usr/local/share/ca-certificates \
    && update-ca-certificates
ENV REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt

# Miniconda setup
RUN bash Docker/miniconda_install.sh
ENV CONDA_PLUGINS_AUTO_ACCEPT_TOS=true

RUN . "$HOME/miniconda3/bin/activate" \
    && conda config --add channels conda-forge \
    && conda update -q --all -y \
    && conda install python=3.11 -q -y

RUN . "$HOME/miniconda3/bin/activate" \
    && conda install gcc=14 gxx ffmpeg cmake unzip -q -y

RUN "$HOME/miniconda3/bin/pip" cache purge
RUN rm -rf "$HOME/miniconda3/pkgs" \
    && mkdir -p "$HOME/miniconda3/pkgs" \
    && rm -rf "$HOME/.conda" "$HOME/.cache"

# Python packages install
RUN "$HOME/miniconda3/bin/pip" install \
    /apex-1.9.0a0+rocm7.1.0.git07c3ee53-cp311-cp311-linux_x86_64.whl \
    /torch-2.9.1+rocm7.1.0.lw.git351ff442-cp311-cp311-linux_x86_64.whl \
    /torchaudio-2.9.0+rocm7.1.0.gite3c6ee2b-cp311-cp311-linux_x86_64.whl \
    /torchvision-0.24.0+rocm7.1.0.gitb919bd0c-cp311-cp311-linux_x86_64.whl \
    /triton-3.5.1+rocm7.1.0.gita272dfa8-cp311-cp311-linux_x86_64.whl \
    --root-user-action ignore

RUN . "$HOME/miniconda3/bin/activate" \
    && bash Docker/install_torchcodec_rocm.sh

COPY extra-req.txt requirements.txt install.sh /workspace/GPT-SoVITS/

# RUN bash Docker/install_wrapper_amd.sh
ENV TERM=xterm-256color
RUN mkdir -p GPT_SoVITS/text

RUN . "$HOME/miniconda3/bin/activate" \
    && bash install.sh --device "ROCM" --source HF

RUN "$HOME/miniconda3/bin/pip" cache purge \
    && rm -rf /tmp/* /var/tmp/* \
    && rm -rf "$HOME/miniconda3/pkgs" \
    && mkdir -p "$HOME/miniconda3/pkgs" \
    && rm -rf /root/.conda /root/.cache

WORKDIR /workspace
RUN mkdir -p /workspace/models \
    && mv /workspace/GPT-SoVITS/GPT_SoVITS/pretrained_models \
    /workspace/GPT-SoVITS/GPT_SoVITS/text/G2PWModel \
    /workspace/models/ \
    && rm -rf /workspace/GPT-SoVITS

WORKDIR /workspace/GPT-SoVITS

COPY . /workspace/GPT-SoVITS

# RUN ls -la

RUN rm -rf /workspace/GPT-SoVITS/GPT_SoVITS/pretrained_models && \
    rm -rf /workspace/GPT-SoVITS/GPT_SoVITS/text/G2PWModel && \
    rm -rf /workspace/GPT-SoVITS/tools/asr/models && \
    rm -rf /workspace/GPT-SoVITS/tools/uvr5/uvr5_weights && \
    ln -s /workspace/models/pretrained_models /workspace/GPT-SoVITS/GPT_SoVITS/pretrained_models && \
    ln -s /workspace/models/G2PWModel /workspace/GPT-SoVITS/GPT_SoVITS/text/G2PWModel && \
    ln -s /workspace/models/asr_models /workspace/GPT-SoVITS/tools/asr/models && \
    ln -s /workspace/models/uvr5_weights /workspace/GPT-SoVITS/tools/uvr5/uvr5_weights

EXPOSE 9871 9872 9873 9874 9880
CMD ["/bin/bash"]
